fix(_client): fix AttributeError
when __init__ raised an error ,sdk would raise AttributeError: 'ZhipuAI' object has no attribute '_client', which is not excepted. fixed